#!/bin/sh
#
# backup: This script defines the default backup mechanism function and should be overloaded by downstream controls

container_backup() {
 /bin/cp -vr /mnt/volumes/container/* ./
 /bin/rm -rf ./cache/
 /bin/rm -rf ./dist/
 /bin/rm -rf ./libraries/
 /bin/rm -rf ./logs/*.log.gz
 /bin/rm -rf ./node_modules
 /bin/rm -rf ./versions/
 return $?
}
