#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)


container_version() {
 MINECRAFT="$(/bin/ls /opt/minecraft/paper* | /usr/bin/awk -F '-' '{print $2}')"
 PAPER="$(/bin/ls /opt/minecraft/paper* | /usr/bin/awk -F '-' '{print $3}' | /usr/bin/awk -F '.' '{print $1}')"
 echo "$MINECARFT-$PAPER"
}

container_entrypoint() {
 /bin/echo "Launch Minecraft Server(paper) in screen [Use 'screen -x' to attach]"
 cd /opt/minecraft
 /usr/bin/screen -m /usr/bin/java -jar paper-1.20.4-409.jar
 # /bin/echo "General blocking function."
 # /usr/bin/tail -f /dev/null
}
