#!/bin/sh
export DOCKER_HOST=amd64-docker.gautier.local
docker build --tag minecraft:build . --no-cache 
docker run -d --rm --name minecraft minecraft:build
docker stop minecraft
docker tag minecraft:build gautada/minecraft:1.16.5
docker push gautada/minecraft:1.16.5




